language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
addons:
  apt:
    packages:
      - default-jre
before_install:
  - npm install -g npm@latest-2
after_success:
  - npm run coverage
  - npm run semantic-release
